export const PLANE_LIST_REQUEST = "PLANE_LIST_REQUEST"
export const PLANE_LIST_SUCCESS = "PLANE_LIST_SUCCESS"
export const PLANE_LIST_FAIL = "PLANE_LIST_FAIL"

export const PLANE_EDIT_REQUEST = "PLANE_EDIT_REQUEST"
export const PLANE_EDIT_SUCCESS = "PLANE_EDIT_SUCCESS"
export const PLANE_EDIT_FAIL = "PLANE_EDIT_FAIL"

export const PLANE_DELETE_REQUEST = "PLANE_DELETE_REQUEST"
export const PLANE_DELETE_SUCCESS = "PLANE_DELETE_SUCCESS"
export const PLANE_DELETE_FAIL = "PLANE_DELETE_FAIL"

export const PLANE_CREATE_REQUEST = "PLANE_CREATE_REQUEST"
export const PLANE_CREATE_SUCCESS = "PLANE_CREATE_SUCCESS"
export const PLANE_CREATE_FAIL = "PLANE_CREATE_FAIL"
export const PLANE_CREATE_RESET = "PLANE_CREATE_RESET"